set(_CATKIN_CURRENT_PACKAGE "gazebo_3d_laser_plugin")
set(gazebo_3d_laser_plugin_VERSION "0.0.0")
set(gazebo_3d_laser_plugin_MAINTAINER "adithya <adithya@todo.todo>")
set(gazebo_3d_laser_plugin_PACKAGE_FORMAT "2")
set(gazebo_3d_laser_plugin_BUILD_DEPENDS "gazebo_plugins" "gazebo_ros" "roscpp" "gazebo_dev" "message_generation" "gazebo_msgs" "geometry_msgs" "sensor_msgs" "std_srvs" "rospy" "angles" "nav_msgs" "urdf" "tf" "tf2_ros" "std_msgs")
set(gazebo_3d_laser_plugin_BUILD_EXPORT_DEPENDS "gazebo_plugins" "gazebo_ros" "roscpp" "gazebo_msgs" "geometry_msgs" "sensor_msgs" "std_srvs" "rospy" "angles" "nav_msgs" "urdf" "tf" "tf2_ros" "std_msgs")
set(gazebo_3d_laser_plugin_BUILDTOOL_DEPENDS "catkin")
set(gazebo_3d_laser_plugin_BUILDTOOL_EXPORT_DEPENDS )
set(gazebo_3d_laser_plugin_EXEC_DEPENDS "gazebo_plugins" "gazebo_ros" "roscpp" "gazebo_dev" "message_runtime" "gazebo_msgs" "geometry_msgs" "sensor_msgs" "std_srvs" "rospy" "angles" "nav_msgs" "urdf" "tf" "tf2_ros" "std_msgs")
set(gazebo_3d_laser_plugin_RUN_DEPENDS "gazebo_plugins" "gazebo_ros" "roscpp" "gazebo_dev" "message_runtime" "gazebo_msgs" "geometry_msgs" "sensor_msgs" "std_srvs" "rospy" "angles" "nav_msgs" "urdf" "tf" "tf2_ros" "std_msgs")
set(gazebo_3d_laser_plugin_TEST_DEPENDS )
set(gazebo_3d_laser_plugin_DOC_DEPENDS )
set(gazebo_3d_laser_plugin_URL_WEBSITE "")
set(gazebo_3d_laser_plugin_URL_BUGTRACKER "")
set(gazebo_3d_laser_plugin_URL_REPOSITORY "")
set(gazebo_3d_laser_plugin_DEPRECATED "")