(cl:defpackage mav_msgs-msg
  (:use )
  (:export
   "<COMMANDATTITUDETHRUST>"
   "COMMANDATTITUDETHRUST"
   "<COMMANDMOTORSPEED>"
   "COMMANDMOTORSPEED"
   "<COMMANDRATETHRUST>"
   "COMMANDRATETHRUST"
   "<COMMANDROLLPITCHYAWRATETHRUST>"
   "COMMANDROLLPITCHYAWRATETHRUST"
   "<COMMANDTRAJECTORY>"
   "COMMANDTRAJECTORY"
   "<COMMANDVELOCITYTRAJECTORY>"
   "COMMANDVELOCITYTRAJECTORY"
   "<MOTORSPEED>"
   "MOTORSPEED"
  ))

