set(_CATKIN_CURRENT_PACKAGE "SetPoseforObjects")
set(SetPoseforObjects_VERSION "0.0.0")
set(SetPoseforObjects_MAINTAINER "adithya <adithya@todo.todo>")
set(SetPoseforObjects_PACKAGE_FORMAT "2")
set(SetPoseforObjects_BUILD_DEPENDS "gazebo_msgs" "gazebo_plugins" "gazebo_ros" "roscpp" "rospy" "message_generation" "gazebo_dev")
set(SetPoseforObjects_BUILD_EXPORT_DEPENDS "gazebo_msgs" "gazebo_plugins" "gazebo_ros" "roscpp" "rospy" "gazebo_dev")
set(SetPoseforObjects_BUILDTOOL_DEPENDS "catkin")
set(SetPoseforObjects_BUILDTOOL_EXPORT_DEPENDS )
set(SetPoseforObjects_EXEC_DEPENDS "gazebo_msgs" "gazebo_plugins" "gazebo_ros" "roscpp" "rospy" "message_runtime" "gazebo_dev")
set(SetPoseforObjects_RUN_DEPENDS "gazebo_msgs" "gazebo_plugins" "gazebo_ros" "roscpp" "rospy" "message_runtime" "gazebo_dev")
set(SetPoseforObjects_TEST_DEPENDS )
set(SetPoseforObjects_DOC_DEPENDS )
set(SetPoseforObjects_URL_WEBSITE "")
set(SetPoseforObjects_URL_BUGTRACKER "")
set(SetPoseforObjects_URL_REPOSITORY "")
set(SetPoseforObjects_DEPRECATED "")