set(SetPoseforObjects_SETUP_PY_VERSION "0.0.0")
set(SetPoseforObjects_SETUP_PY_SCRIPTS "")
set(SetPoseforObjects_SETUP_PY_PACKAGES "SetPoseforObjects")
set(SetPoseforObjects_SETUP_PY_PACKAGE_DIRS "src/SetPoseforObjects")
set(SetPoseforObjects_SETUP_PY_MODULES "")
set(SetPoseforObjects_SETUP_PY_MODULE_DIRS "")