// Generated by gencpp from file SetPoseforObjects/MoveToPtrRequest.msg
// DO NOT EDIT!


#ifndef SETPOSEFOROBJECTS_MESSAGE_MOVETOPTRREQUEST_H
#define SETPOSEFOROBJECTS_MESSAGE_MOVETOPTRREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace SetPoseforObjects
{
template <class ContainerAllocator>
struct MoveToPtrRequest_
{
  typedef MoveToPtrRequest_<ContainerAllocator> Type;

  MoveToPtrRequest_()
    : px()  {
    }
  MoveToPtrRequest_(const ContainerAllocator& _alloc)
    : px(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _px_type;
  _px_type px;





  typedef boost::shared_ptr< ::SetPoseforObjects::MoveToPtrRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::SetPoseforObjects::MoveToPtrRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToPtrRequest_

typedef ::SetPoseforObjects::MoveToPtrRequest_<std::allocator<void> > MoveToPtrRequest;

typedef boost::shared_ptr< ::SetPoseforObjects::MoveToPtrRequest > MoveToPtrRequestPtr;
typedef boost::shared_ptr< ::SetPoseforObjects::MoveToPtrRequest const> MoveToPtrRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::SetPoseforObjects::MoveToPtrRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::SetPoseforObjects::MoveToPtrRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace SetPoseforObjects

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'gazebo_msgs': ['/home/adithya/ReinfLearn/gym/gym-gazebo/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/gazebo_ros_pkgs/gazebo_msgs/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::SetPoseforObjects::MoveToPtrRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::SetPoseforObjects::MoveToPtrRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::SetPoseforObjects::MoveToPtrRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::SetPoseforObjects::MoveToPtrRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::SetPoseforObjects::MoveToPtrRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::SetPoseforObjects::MoveToPtrRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::SetPoseforObjects::MoveToPtrRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86d2eb22b38cc7741e0ddd8b5bb94d82";
  }

  static const char* value(const ::SetPoseforObjects::MoveToPtrRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86d2eb22b38cc774ULL;
  static const uint64_t static_value2 = 0x1e0ddd8b5bb94d82ULL;
};

template<class ContainerAllocator>
struct DataType< ::SetPoseforObjects::MoveToPtrRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "SetPoseforObjects/MoveToPtrRequest";
  }

  static const char* value(const ::SetPoseforObjects::MoveToPtrRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::SetPoseforObjects::MoveToPtrRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose px\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::SetPoseforObjects::MoveToPtrRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::SetPoseforObjects::MoveToPtrRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.px);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToPtrRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::SetPoseforObjects::MoveToPtrRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::SetPoseforObjects::MoveToPtrRequest_<ContainerAllocator>& v)
  {
    s << indent << "px: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.px);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SETPOSEFOROBJECTS_MESSAGE_MOVETOPTRREQUEST_H
