// Generated by gencpp from file SetPoseforObjects/MoveToPtrResponse.msg
// DO NOT EDIT!


#ifndef SETPOSEFOROBJECTS_MESSAGE_MOVETOPTRRESPONSE_H
#define SETPOSEFOROBJECTS_MESSAGE_MOVETOPTRRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace SetPoseforObjects
{
template <class ContainerAllocator>
struct MoveToPtrResponse_
{
  typedef MoveToPtrResponse_<ContainerAllocator> Type;

  MoveToPtrResponse_()
    : done(false)  {
    }
  MoveToPtrResponse_(const ContainerAllocator& _alloc)
    : done(false)  {
  (void)_alloc;
    }



   typedef uint8_t _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::SetPoseforObjects::MoveToPtrResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::SetPoseforObjects::MoveToPtrResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToPtrResponse_

typedef ::SetPoseforObjects::MoveToPtrResponse_<std::allocator<void> > MoveToPtrResponse;

typedef boost::shared_ptr< ::SetPoseforObjects::MoveToPtrResponse > MoveToPtrResponsePtr;
typedef boost::shared_ptr< ::SetPoseforObjects::MoveToPtrResponse const> MoveToPtrResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::SetPoseforObjects::MoveToPtrResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::SetPoseforObjects::MoveToPtrResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace SetPoseforObjects

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'gazebo_msgs': ['/home/adithya/ReinfLearn/gym/gym-gazebo/gym-gazebo/gym_gazebo/envs/installation/catkin_ws/src/gazebo_ros_pkgs/gazebo_msgs/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::SetPoseforObjects::MoveToPtrResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::SetPoseforObjects::MoveToPtrResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::SetPoseforObjects::MoveToPtrResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::SetPoseforObjects::MoveToPtrResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::SetPoseforObjects::MoveToPtrResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::SetPoseforObjects::MoveToPtrResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::SetPoseforObjects::MoveToPtrResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89bb254424e4cffedbf494e7b0ddbfea";
  }

  static const char* value(const ::SetPoseforObjects::MoveToPtrResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89bb254424e4cffeULL;
  static const uint64_t static_value2 = 0xdbf494e7b0ddbfeaULL;
};

template<class ContainerAllocator>
struct DataType< ::SetPoseforObjects::MoveToPtrResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "SetPoseforObjects/MoveToPtrResponse";
  }

  static const char* value(const ::SetPoseforObjects::MoveToPtrResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::SetPoseforObjects::MoveToPtrResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool done\n\
\n\
";
  }

  static const char* value(const ::SetPoseforObjects::MoveToPtrResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::SetPoseforObjects::MoveToPtrResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToPtrResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::SetPoseforObjects::MoveToPtrResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::SetPoseforObjects::MoveToPtrResponse_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SETPOSEFOROBJECTS_MESSAGE_MOVETOPTRRESPONSE_H
